[package]
name = "table-ocr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
csv = "1.4.0"
image = "0.25.9"
imageproc = "0.27.0"
leptess = "0.14.0"
rayon = "1.11.0"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "image_processing"
harness = false
